# name of the workflow
name: Run Python Program

#Define Trigger
on:
  push:
      branches:
        -main

jobs:
    ci-pipeline:
        runs-on: ubuntu-latest

        steps:
        - name: checkout code
          uses: actions/checkout@v2

        - name: print welcome message 
          run: echo 'welcome to github action'
